CREATE TABLE [Articles]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Title] VARCHAR(400) NOT NULL,
    [CreateDate] DATETIME NOT NULL DEFAULT(GETDATE()),
    [PublishedData] DATETIME NOT NULL DEFAULT(GETDATE()),
	[Site] VARCHAR(500) NOT NULL,
	[AdGroup] VARCHAR(500) NOT NULL,
	[Bids] DECIMAL(10, 2) NOT NULL,
	[Spending] DECIMAL(10, 2) NOT NULL,
	[WinRate] DECIMAL(10, 2) NOT NULL,
	[Impressions] DECIMAL(10, 2) NOT NULL,
	[Clicks] int NOT NULL,
	[CTR] DECIMAL(10, 2) NOT NULL
)